### ISSUE TITLE
Квадратные уравнения, makefile и gitignore

### ISSUE THREAD

**Issue by DashProk1407** [DashProk1407/repoz#1]
to: @evgeny-p

**Comment by evgeny-p** [comment]
Некоторые замечания были озвучены на паре, но для надежности зафиксирую их здесь.
1. Напомню, что коэффициенты уравнения, корни и дискриминант — числа с плавающей точкой.
2. Неясна семантика возвращаемого значения функции `equ`.
3. Заголовочный файл `equ.h` также должен подключаться в `equ.c`.
4. Неконсистентное форматирование: лишний пробел между `main` и открывающей круглой скобкой.

**Comment by evgeny-p** [comment]
Работы 2 и 4 приняты.
